name: Build Project


on: [push]

jobs:
  build:
    name: Run full lint checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: Run Mage
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: go:test go:lint
